version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: node:lts
    container_name: gemini-ai-custom-function
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    tty: true

